-- Editorial generation metadata + cross-company theme labels.
--
-- Editorial generation runs from `web/lib/analysis/company-editorial.ts`. We
-- track the prompt version + model + timestamp so a stale company can be
-- refreshed by a scheduled job (`web/scripts/regenerate-editorial.ts`).
--
-- Cross-company themes get author-quality labels from the LLM theme labeler
-- (`web/lib/analysis/cross-company-themes.ts`). Cached here keyed by the
-- function group; refreshed weekly.

ALTER TABLE companies
  ADD COLUMN IF NOT EXISTS editorial_generated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS editorial_prompt_version TEXT,
  ADD COLUMN IF NOT EXISTS editorial_model TEXT;

COMMENT ON COLUMN companies.editorial_generated_at IS
  'When companies.thesis / interpretation / bets were last generated by the editorial engine.';
COMMENT ON COLUMN companies.editorial_prompt_version IS
  'Prompt version of the editorial run that produced the current thesis/bets.';
COMMENT ON COLUMN companies.editorial_model IS
  'Gemini model used for the editorial run (e.g. gemini-pro-latest).';

CREATE TABLE IF NOT EXISTS cross_company_themes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category_group TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  description TEXT,
  keywords_hash TEXT,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  prompt_version TEXT,
  model TEXT
);

COMMENT ON TABLE cross_company_themes IS
  'LLM-generated editorial labels for the function-category groups surfaced on the Jobs right rail. One row per group; refreshed weekly.';
COMMENT ON COLUMN cross_company_themes.category_group IS
  'Matches getCategoryGroup() output (engineering / product-design / data-science / etc.).';
COMMENT ON COLUMN cross_company_themes.label IS
  'Editorial label such as "Real-time payments rails" or "In-house card issuing".';
COMMENT ON COLUMN cross_company_themes.description IS
  'One-sentence explainer of what the theme means for industry observers.';
COMMENT ON COLUMN cross_company_themes.keywords_hash IS
  'Hash of the keyword bag used to derive the label. When the bag changes, the label is regenerated.';

CREATE INDEX IF NOT EXISTS cross_company_themes_generated_at_idx
  ON cross_company_themes (generated_at DESC);
